### ISSUE TITLE
Add-UIPathUser not working for domain user.

### ISSUE THREAD

**Issue by loicmitton** [UiPath/orchestrator-powershell#35]
Hello,

We tried to use the example to sync user and we found that Add-UiPathUser don't have a domain parameter.
After we tested the script, account were created with domain\login format but it was not possible to authenticate as Windows account with them.

**Comment by rusanu** [comment]
You are correct. I will push a fix.
The sync script will continue to add users as `domain\user` name, because this is the only way that the Domain users can be later recognized in order for the sync to work (remove users from groups, remove users from Orchestartor). This is not how Orchestartor itself imports the users, but I think the Orchestor import is broken and a bad example (eg. it cannot import trusted domains).
