### ISSUE TITLE
Authtoken with windows credential failing: Unauthorized 

### ISSUE THREAD

**Issue by ekalkst** [UiPath/orchestrator-powershell#6]
Used get-uipathauthtoken with -WindowsCredetnials and -Session in parameters.  Get a response but the next call will fail

![uipathps](https://user-images.githubusercontent.com/42302582/45763866-704dc680-bbff-11e8-8846-7583c668d5c0.JPG)

**Comment by DRCawthon** [comment]
Getting the same thing. Any ETA on a solution?

**Comment by rusanu** [comment]
@DRCawthon let me make sure I understand: you are getting a Windows Authentication token, and at the first use you are getting an authentication error?

**Comment by DRCawthon** [comment]
Yes correct. In my first screenshot you can see that i put the token into a variable but the actual token field is empty. Whenever i try to use it to upload a package i get the error you see in the 2nd screenshot that Im not authorized.

**Comment by rusanu** [comment]
This issue here is simply about the problem that `Get-UiPathAuthToken`  should fail if the user is not authorized, not return a success token that fails when tried to be used.

But in your case, It looks like that you are not authorized. Are you trying to debug/troubleshoot why are you not authorized?

**Comment by DRCawthon** [comment]
I should be authorized. Im an Admin in the Orchestrator instance. Even if I try to use username and password of admin account (i installed Orchestrator) i get the same null token.

**Comment by Michel001** [comment]
i have the same problem at DRCAwthon.
When i use 
_Get-UiPathAuthToken -URL https://domain -Username admin -Password password -Session -verbose_
i get a token but when i do
Get-UiPathAuthToken -URL https://domain -WindowsCredentials -Session -verbose
i get no token but no errors either i get the same as the above pictures.
the powershell user is at that moment also an administrator on the Orchestrator instance.

**Comment by nlmaca** [comment]
Is there any news on this? im experiencing the same problem.

**Comment by rusanu** [comment]
Resolving this since does not reflect a problem with the library and is non-actionable. All cases I looked are were incorrect assumptions (Azure AD vs. AD), legit authentication issues (user had no access) or old Orchestrator deployments (18.1 with OU enabled does not work with AD auth for API calls)
